### PR TITLE
Add preview to README

### PR DESCRIPTION
**Pull request by L-as**
I added a preview to the README, see https://github.com/L-as/cinny/tree/87d5cb78b2590d73ee338c783eff09193ff1db91 to see how it looks.

### CODE REVIEW

**Comment by kfiven** [comment]
Instead of uploading to this repo why not use file directly from site repo?

**Comment by L-as** [comment]
That would mean it has to be fetched from an external domain.

**Comment by kfiven** [comment]
I meant [this](https://github.com/ajbura/cinny-site/blob/master/assets/preview-light.png) from site repo.

**Review by kfiven — APPROVED** [review]

**Comment by L-as** [comment]
Thanks.

**Pull request merged**
