### PR TITLE
Drag and drop files

### LINKED ISSUE #85: Drag-and-drop file upload & message field autofocus
#### Is your feature request related to a problem? Please describe.
I always want to drag an image onto the message field, to attach it to my message, but instead my browser opens the file as a `file://` link.

I also wish that the message field was focused after uploading a file so that you don't need to tab to it after upload.

#### Describe the solution you'd like
I would hope that dragging a file on top of the message field attached the file + after attaching a file, the message `<input/>` was focused.

#### Additional context

Thanks for this awesome project! I'd be interested in implementing at least part of this, but I haven't actually looked too much at the structure of the app... it looks quite nicely laid out though

### PR DESCRIPTION
**Pull request by ginnyTheCat**
### Description

Allow to drop files on the page to upload them to the composer.

Dragging an image
image

After droping the image
image
(the orange rectangle border is probably a Firefox bug)

It currently does not draw a overlay like discord or element does. I'll probably add one.

Fixes #85

#### Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

Preview: https://61f96ed1da86830b2137e03b--pr-cinny.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Review by ajbura — APPROVED** [review]

**Comment by ginnyTheCat** [comment]
Should I still add an overlay like other chat apps do or do like it more like it is now?
I added an example how this could look to the [drop branch](https://github.com/ginnyTheCat/cinny/tree/drop) and on [cinny.lelux.net](https://cinny.lelux.net). 
The design is just a placeholder right now.

**Comment by ajbura** [comment]
Looks great. It would be a great addition. Thanks! :)

**Comment by ginnyTheCat** [comment]
I'm gonna redesign it a bit and create a seperate PR when it's ready

**Comment by ajbura** [comment]
@ginnyTheCat One bug i found while using dev.cinny.in is when you select text drag it and then drop, it will crash the app.

**Comment by ginnyTheCat** [comment]
I fixed it in the `drop` branch.

**Comment by ginnyTheCat** [comment]
Should I create a seperate branch or PR with just the patch so it's easier for you to merge it?

**Comment by ajbura** [comment]
yeah sure

**Pull request merged**
