### PR TITLE
String update and file extension name consistency

### LINKED ISSUE #433: Confusing room security descriptions
### Describe the problem

image
The language used to describe these options is somewhat confusing.

### Describe the solution you'd like

Rephrase the text for the options.

### Alternatives considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kfiven**
### Description
Updated strings to be less confusing and use .yaml instead of .yml for all files for consistency.

Also disabled auto-labelling of issues as it may produce wrong labelling sometimes.

Fixes #433, 432, 434

Preview: https://62440f4f5dfc3c4d66b2bd01--pr-cinny.netlify.app
⚠️ Exercise caution. Use test accounts. ⚠️

### CODE REVIEW

**Comment by ajbura** [comment]
@AveryTheFurry Are these ok now?

**Review by ajbura — APPROVED** [review]

**Comment by kfiven** [comment]
One problem I found with these that they get truncated on small screens.

So thought of alternative:

* Anyone (including guests)
* Members (all messages)
* Members (messages after invite)
* Members (messages after join)

**Comment by kfiven** [comment]
Could you please check again @ajbura ?

**Comment by ajbura** [comment]
Looks better than before 👍

**Pull request merged**
