### PR TITLE
Add support for building docker image for linux/arm64

### LINKED ISSUE #489: [feat] Multi platform docker image
### Describe the problem

Docker image is only available for amd64

### Describe the solution you'd like

Use existing github action to build and push multi platform images.
add platforms to prod-deploy.yml

for example:
```
      - name: Build and push Docker image
        uses: docker/build-push-action@v2.10.0
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```

### Alternatives considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kfiven**
### Description
This PR add support to build docker image for linux/arm64 platform. Currently we only have it for linux/amd64.

Fixes #489

#### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

Preview: https://6291e81eb669225c2ec924b6--pr-cinny.netlify.app
⚠️ Exercise caution. Use test accounts. ⚠️

### CODE REVIEW

**Comment by kfiven** [comment]
Btw build times has gone 10x, and I don't know why.

**Review by GoliathLabs — CHANGES_REQUESTED** [review]
@kfiven, since we use qemu to build arm64 (a non-native platform for the gh-action VMs), it takes much longer. It would be recommended to build arm64 images only when a new tag is pushed (as possibly multiple build processes can run at the same time and overwrite the other one, depending on which one finishes first)

**Comment by anthr76** [comment]
I would like to have this merged as I have a multi-arch Kubernetes cluster I would like to deploy this on.

**Comment by ivanjx** [comment]
why not just build with whatever system you are running on then just use the arm64 of nginx for example?

**Comment by ajbura** [comment]
linux/arm/v7 is also requested in issue #489, is it possible to build that also?

**Comment by kfiven** [comment]
No, we have a dependency that needs a library that is not available on arm/v7 yet https://github.com/kfiven/cinny/runs/6072704815?check_suite_focus=true#step:7:565

```
 > [linux/arm/v7 builder 4/6] RUN npm ci:
#31 421.6 npm ERR! code 1
#31 421.6 npm ERR! path /src/node_modules/sharp
#31 421.6 npm ERR! command failed
#31 421.6 npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
#31 421.6 npm ERR! sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.10.6/libvips-8.10.6-linuxmusl-armv7.tar.br
#31 421.6 npm ERR! sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
#31 421.6 npm ERR! sharp: Installation error: Prebuilt libvips 8.10.6 binaries are not yet available for linuxmusl-armv7
```

**Review by ajbura — APPROVED** [review]

**Pull request merged**
