### PR TITLE
Basic spoiler markdown plugin

### LINKED ISSUE #177: spoiler creation support
#### Is your feature request related to a problem? Please describe.
being able to send spoiler text from cinny

#### Describe the solution you'd like
`||text||` -> plain `(Spoiler: text)` or something, html `<span data-mx-spoiler>text</span>`

#### Describe alternatives you've considered
<span data-mx-spoiler>text</spoiler> - ew verbose
<spoiler>text</spoiler> - ew still verbose, and has no grounds in matrix

#### Additional context
discord uses ||
afaik element has no way to create it besides a command (for the whole message)
not part of commonmark so custom parsing is probably needed

### PR DESCRIPTION
**Pull request by ginnyTheCat**
### Description

This change adds a custom micromark extension allowing the use of discord-style markdown spoilers. In case a different style of spoilers is preferred I would have no problem adapting the extension to these new tasks.

Sending `snape kills ||somebody||` with markdown mode enabled will result in `snape kills <span data-mx-spoiler>somebody</span>` being sent.

image

The feature is not fully complete yet as the extension code is still very messy and the parser might mess things up in some edge cases. Hiding the spoiler message in the plaintext body is missing as well (it's in the spec; element android/web doesn't do it).

Fixes #177

#### Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

Preview: https://61f411375d675fed5078a1a7--pr-cinny.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Comment by ajbura** [comment]
IMHO we should add spoiler support (and possibly bold, italics, and more text formatting options) with a custom input (aka editor like slack). So my plan was to work on this by making a Custom Message Input and leverage it for spoilers too.

Though I have no issues having this as a temporary solution and wouldn’t recommend building something complex on it.

**Comment by ginnyTheCat** [comment]
Sounds great! Just curious if the editor would have an option to still use markdown (like GitHub does it) or if it would be completely hidden from the user?
As a temporary solution it's probably already good enough.

**Comment by ajbura** [comment]
> Just curious if the editor would have an option to still use markdown (like GitHub does it) or if it would be completely hidden from the user?
 Haven't thought much but it probably will be mix of both, so markdown still be visible but user pills, room alias etc will not.

**Comment by ajbura** [comment]
> Just curious if the editor would have an option to still use markdown (like GitHub does it) or if it would be completely hidden from the user?

Haven't thought much but it probably will be mix of both, so markdown still be visible but user pills, room alias etc will not.

**Review by ajbura — APPROVED** [review]
Looks good.

**Comment by ajbura** [comment]
Could you rebase it with latest commits in dev?

**Pull request merged**
