### PR TITLE
Show devices without encryption support separately from unverified session

### PR DESCRIPTION
**Pull request by ginnyTheCat**
### Description

Cinny marks devices without encryption support as not verified. They however are unable to be verified. The warning is therefore not very useful (as there is no way to fix it, and the device not having access to encrypted messages to begin with).

Element Web also does this
image

This also makes these devices not appear in the "unverified sessions" warning in the navigation bar.

Before:
image

After:
image

#### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

Preview: https://62657afdcc0e5743464f5e2c--pr-cinny.netlify.app
⚠️ Exercise caution. Use test accounts. ⚠️

### CODE REVIEW

**Comment by ajbura** [comment]
we can also remove the red text color for them

**Comment by ginnyTheCat** [comment]
I like the red text as it shows that it's still not really as secure as it should/could be.
Still I wouldn't mind changing it.

**Comment by ajbura** [comment]
I choose the red color so it prompt user to verify the session. but if we can't verify it, it will create disturbance.

Apart from this we still gonna have that (unverified session)alert on sidebar for can't verify sessions? EDITED: ok i see it 👍

**Comment by ginnyTheCat** [comment]
>Apart from this we still gonna have that (unverified session)alert on sidebar for can't verify sessions?

No, that was the main reason I created this fix.

**Review by ajbura — APPROVED** [review]

**Pull request merged**
