### PR TITLE
Fix typos and wording

### PR DESCRIPTION
**Pull request by moritzdietz**
# Description

As in the repo for the website, I took the liberty to fix some spelling and grammar mistakes.
Additionally I changed the wording of the password policy.

Note: I haven't yet checked if the length of the strings somehow clash with the UI causing UX regressions in terms of overlapping etc.

### CODE REVIEW

**Comment by farribeiro** [comment]
LGTM

**Comment by moritzdietz** [comment]
Yeah I just checked and this seems to work:
image

**Comment by moritzdietz** [comment]
Yeah this looks good. Doesn't break visually IMO
image

**Comment by moritzdietz** [comment]
I just noticed something regarding the password strings and fixed it. Element Web has the same wording so I updated it.

**Review by ajbura — APPROVED** [review]

**Pull request merged**
