### PR TITLE
Temporary jitsi calls

### PR DESCRIPTION
**Pull request by IceDBorn**
Following discord's new privacy guidelines, I decided to switch to Cinny because it is the matrix client most like Discord. Unfortunately, Cinny does not support voice/video calls which is why I chose to create a temporary solution myself with the help of some friends. The aim of this draft is not to be merged with Cinny, but to present users with a temporary way to make calls on Cinny until it is officially implemented.

We are very open to implementing any refactoring and fixes submitted by the community on this fork.

image

image

image

image

### CODE REVIEW

**Comment by IceDBorn** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by CrazyStevenz** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by jim3692** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by kfiven** [comment]
Closing as the author intended this to be not merged.

**Pull request closed without merging**
