### PR TITLE
Combine cinny-desktop

### PR DESCRIPTION
**Pull request by HybridEidolon**
### Description

Merge the cinny-desktop tree into the main app tree, allowing the Tauri app to be built inside the tree with the app itself. Provides #1323 .

This merge intentionally preserves the commit history of cinny-desktop to maintain authorship information for AGPL-3 compliance.

Fixes #

#### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist:

(Most N/A)

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by kubo6472** [comment]
The merged README wouldn't make sense anyway. You can drop my commit as I won't be signing any kind of CLA, thanks. @HybridEidolon

**Comment by kubo6472** [comment]
recheck

**Comment by JuliaSoriaSmith** [comment]
I think there is merit for merging the two together, so you can work on it as a single package with a unified review process. It would nice to be able to fork this repo and compile to a desktop app whilst still having the ability to post changes.

**Comment by kfiven** [comment]
Closing as we do not have any plans to combine these two and that's why we started the desktop repo as separate in starting.

**Pull request closed without merging**
