### PR TITLE
Draft: Initial tauri version of Cinny

### LINKED ISSUE #53: Native application using Electron or Tauri
#### Is your feature request related to a problem? Please describe.

Cinny is only available as a pure web application that must run in a browser, and cannot be started in a "desktop" fashion like other messaging desktop apps.

#### Describe the solution you'd like

A desktop version of Cinny, which can be installed locally and run outside a traditional browser. For instance, by packaging Cinny with Electron, to mimic what element-desktop is doing.

Running in such a "desktop mode" would also mean that Cinny would be loaded/run locally, which is a nice bonus.

#### Describe alternatives you've considered

The provided docker image is really nice, and does provide a way to run Cinny locally with little effort. But it does not answer the original problem, namely that Cinny has to be used in a browser, and not in its own separate window.

### PR DESCRIPTION
**Pull request by MTRNord**
### Description

This adds a Desktop version to Cinny.

Fixes #53 

#### Why Tauri instead of electron?

The reason is simply that tauri is more modern, self contained, uses far less resources and produces much smaller binaries.

Downside is that there are less plugins yet.

#### How to build the Tauri version (Doc update will follow)

1. Follow any of the setup guides on https://tauri.studio/en/docs/getting-started/intro for your platform
2. For testing you need to run `npm start` first to have the dev server running and then you can run tauri using `npm run tauri dev` to get the window. 
3. To build a release version run `npm run tauri build`
4. For auto updates and signing follow https://tauri.studio/en/docs/distribution/updater#update-requests  (Needs discussion likely as well)

#### Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Add CI flows for tauri
- [ ] Add Auto Update Setup (needs infos from maintainers)
- [ ] Check optimal settings for Cinny

### CODE REVIEW

**Comment by VarLad** [comment]
@MTRNord this is really cool!
May I ask, what are the things left in order for this to merge?

**Comment by MTRNord** [comment]
> 
> 
> @MTRNord this is really cool! May I ask, what are the things left in order for this to merge?

Mainly documentation I think and an opinion of the maintainers.

Also asking them if they want to do autoupdates and if so how as it involves that they generate a key and add it as a secret.

**Comment by VarLad** [comment]
I think a lot of folks would love to use Cinny with something like an app. 

@ajbura any opinions on this?

**Comment by ajbura** [comment]
Hi @MTRNord, Indeed its is great to have an app.

What exactly I need to do for auto updates? Also I tried to build locally and it seems it only build for windows, is that intentional?

**Comment by MTRNord** [comment]
> 
> 
> Hi @MTRNord, Indeed its is great to have an app.
> 
> What exactly I need to do for auto updates? 

A number of things actually.

a) We need some endpoint to get those updates. This is documented in https://tauri.studio/en/docs/distribution/updater so there likely needs to be some webserver. I guess if you want I could host it (I also do the fluffychat fdroid repositories currently.) but it needs some CI additionals to upload them to the server
b) For signing there should be a Key set up as documented at https://tauri.studio/en/docs/distribution/updater#signing-updates So the private key and a password would have to be in the secrets of the repo for usage in the release CI job and the public key published for the configuration.

> Also I tried to build locally and it seems it only build for windows, is that intentional?

No that is not intentional. I think it should always work. I will have a look on my linux to figure out why it fails. 🤔

**Comment by VarLad** [comment]
I can try building a Flatpak for Tauri and publish it on Flathub, once Cinny gets a Tauri app

**Comment by VarLad** [comment]
@MTRNord Any update on this?

**Comment by C0ffeeCode** [comment]
I really hope we get a tauri app at some time ;)

**Pull request closed without merging**
