### PR TITLE
Custom homeserver url support

### PR DESCRIPTION
**Pull request by Sleuth56**
### Description

This adds a easier way to change the default homeserver. A user would put their HS URL into the docker file and build the image. I wanted to make this run when the container was started however I couldn't find any resources online to do so.

#### Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by hifi** [comment]
Changing the code on-the-fly isn't ideal. Adding `config.json` support to the application which overrides defaults and is loaded during initialization with XHR is what Element does and works well enough.

**Comment by Sleuth56** [comment]
@ajubra I plan on looking into doing this correctly when I have some time.

**Comment by ajbura** [comment]
Added in a83aecaa69529dbe610712f7eaed5deb272e5fdd

**Comment by Domoel** [comment]
> Changing the code on-the-fly isn't ideal. Adding `config.json` support to the application which overrides defaults and is loaded during initialization with XHR is what Element does and works well enough.

I have some struggle to apply the config.json with my docker setup. I tried the following to mount it when the container is bulding up:

```
    volumes:
         - /volume2/docker/test/config.json:/config.json
```

Unfortunately nothing changed afterwards. So how can one apply the config.json with docker compose?

**Pull request closed without merging**
