### PR TITLE
Show full timestamp on hover

### LINKED ISSUE #684: View specific timestamps of older messages
### Describe the problem

I don't see any way to view the specific timestamp (time and not just date) of messages sent yesterday or earlier. Instead, those messages only display the date. This can be frustrating especially at midnight when all the most recent messages suddenly lose their timestamp in the UI.

### Describe the solution you'd like

I would like to see the time and date of the message for example in a tooltip when hovering over the date displayed in the right edge.

Additionally, maybe consider displaying the time instead of date for all messages of the past 24 hours, rather than messages sent today?

### Alternatives considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ginnyTheCat**
### Description
Shows the full date when hovering over a time of a message or event. It also changes it to not be date anymore for past days as the date can now be found out by hovering over the time.

image

Fixes #684

#### Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

Preview: https://62ed22314d1e7c6b09c6ffc4--pr-cinny.netlify.app
⚠️ Exercise caution. Use test accounts. ⚠️

### CODE REVIEW

**Comment by kfiven** [comment]
The format we planned when this was added was:
* HH:MM AM/PM for the current day.
* Yesterday HH:MM AM/PM for the past one day. (wasn't added)
* DD/MM/YYYY for the rest of the timeline.
And upon hovering over all of these we can see the full timestamp.

Since the date separator scroll with timeline, the HH:MM in all cases gets really confusing and was the reason for date for older messages.

**Comment by ginnyTheCat** [comment]
Should I add the yesterday case in as well?

**Comment by kfiven** [comment]
That'll be good addition.

**Review by ajbura — COMMENTED** [review]
Message component is also used in RoomSearch.jsx so we need to change the time prop to timestamp there also. 

Otherwise looks good

**Review by ajbura — APPROVED** [review]

**Pull request merged**
