### PR TITLE
Fix inconsistent « Welcome to Empty room room » bug on room creation

### LINKED ISSUE #430: Creating a room temporary displays "welcome to empty room"
### Describe the bug

When creating a room, the content of the message area displays « Welcome to empty room »
Going to another room and coming back will change the message to « Welcome to \<room name\> »
image

### Reproduction

1. Create a room with a custom name

### Expected behavior

The welcome message should display the name of the room

### Platform and versions

```shell
1. OS : Debian 11
2. Browser : Firefox Developper Edition 99.0b8
3. Cinny version : dev (9cb13a91cd889320f5044c1921d9a48c1d6a2091)
4. Home server : matrix.org
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by arnopensource**
### Description
Fixes #430 
When creating a room, the welcome message will sometimes mention « Welcome to Empty room room », this pull request try to fix that
The « Empty room » name seems to come from the home server, the problem does not appear in the RoomViewHeader component because the component is subscribed to `cons.events.roomList.ROOM_PROFILE_UPDATED`and update the name of the room

#### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### Notes
This is work in progress
I used the same technique to re-render than in RoomViewHeader but I think I created unnecessary re-renders
The data flow of this part of the app may need to be modified ?

### CODE REVIEW

**Comment by ajbura** [comment]
Hey @abc3354, That didn't work probably because the ROOM_PROFILE_UPDATED get's fired after render but before useEffect get's run and start listening to room profile update.

There is two thing we can do here: 
1. use `useLayoutEffect` hook instead of useEffect. but it can result in bad performance + we gonna re-render the whole timeline even if there is no roomIntro component.
2. Other we can move `genRoomIntro` function code to `RoomIntro`  component itself and listen that event there. this way we will be listening to event where we need it and it won't cause above problems.

**Comment by arnopensource** [comment]
Ok thanks, I'll investigate
I'm currently exploring the RoomViewContent.jsx file to better understand the way the data flows and when it rerenders

**Comment by arnopensource** [comment]
I found an unrelated problem here, maybe it is not the right place to fix it ?
Checked the others event listeners and I'm not sure why the one at line 412 is removed conditionally ?

**Comment by ajbura** [comment]
Look suspicious to me too. maybe it got left out while refactoring things. feel free to remove if it doesn't cause any error.

**Comment by ajbura** [comment]
btw, related #455

**Comment by arnopensource** [comment]
Ok, I will do that too !
Can you assign me #430 and #455 ?

**Comment by arnopensource** [comment]
It seems that my fix has introduced a weird jump in the timeline when paginating from the server :sweat_smile: 
I will investigate some more

**Comment by ajbura** [comment]
For the assign, can you make a comment on #455 ?

**Comment by arnopensource** [comment]
> It seems that my fix has introduced a weird jump in the timeline when paginating from the server sweat_smile

Ok I investigated more and it is not related to the commit, the bug was there before

**Comment by arnopensource** [comment]
This commit fixes #455 
Note : I leaved the topic in both cases because it seems you can set the topic in a dm channel

**Comment by ajbura** [comment]
closing in favour of 3afc068a02e1ea5aac276d1bc2934d26f07ab599

**Pull request closed without merging**
