### PR TITLE
Fix message box height not restored

### LINKED ISSUE #422: [bug] Message input multiline disappear after room switch
### Describe the bug

When writing a multiline message, if switch to some other room, the multiline height of message input get reset and it appears as if there was no multiline message at all.

### Reproduction

1. Type a multiline message in room's message input
2. switch to another room
3. come back to previous room
4. observe the error

### Expected behavior

_No response_

### Platform and versions

```shell
1.8.2
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by SakiiCode**
### Description

react-autosize-textarea does not re-render when modified with textAreaRef.current.value, so I moved the message box contents out to a state. The textarea height is now properly updated

Fixes #422

#### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by SakiiCode** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by SakiiCode** [comment]
This fix got a bit too complex and contains multiple workarounds. If you don't agree with the solutions provided here, I totally understand that

**Comment by ajbura** [comment]
I am already working on Custom Editor for sending messages.

**Comment by kfiven** [comment]
Fixed in #1190

**Pull request closed without merging**
